### ISSUE TITLE
doc has a broken link

### ISSUE THREAD

**Issue by srl295** [apache/openwhisk-wskdeploy#1013]
[master/docs/wskdeploy_triggerrule_trigger_bindings.md#specification](https://github.com/apache/incubator-openwhisk-wskdeploy/blob/master/docs/wskdeploy_triggerrule_trigger_bindings.md#specification) links to 
non existent [specification/html/spec_trigger_rule.md](https://github.com/apache/incubator-openwhisk-wskdeploy/blob/master/specification/html/spec_trigger_rule.md#triggers-and-rules)

should probably be 2  links to:
- [spec_trigger.md](https://github.com/apache/incubator-openwhisk-wskdeploy/blob/master/specification/html/spec_trigger.md)
- [spec_rule.md](https://github.com/apache/incubator-openwhisk-wskdeploy/blob/master/specification/html/spec_rule.md)

may have been missed  when https://github.com/apache/incubator-openwhisk-wskdeploy/pull/950/commits/9435979a221540f6744b7607980a6655667c347a was done

**Comment by rabbah** [comment]
@mrutkows can you take a look at this and advise? I fixed the links on a branch but the section heading doesn't make sense to me. It reads "For convenience, the Actions and Parameters grammar can be found here:" then links to triggers and rules specs.

**Comment by srl295** [comment]
@mrutkows @rabbah ping, any update on this?

**Comment by rabbah** [comment]
Need Matt to cooment.

**Comment by csantanapr** [comment]
@srl295 could you submit a PR with this change?

**Comment by mrutkows** [comment]
@srl295 will look at asap
