### ISSUE TITLE
Binaries no longer packaged with releases

### ISSUE THREAD

**Issue by Amndeep7** [apache/openwhisk-wskdeploy#1109]
Couldn't find an issue mentioning this, but it seems like the 1.x release line no longer has pre-built binaries attached to them.  Was this an intentional decision and, if so, why?

**Comment by dgrove-oss** [comment]
The wskdeploy functionality was incorporated in `wsk` as a subcommand:  `wsk project [command]`

**Comment by Amndeep7** [comment]
Thanks for the quick response - was able to find the command.  Is there a place to file a bug report on the primary [openwhisk documentation page](https://openwhisk.apache.org/documentation.html)?

`The functionality of wskdeploy is also embedded as the deploy subcommand within the wsk CLI. The functionality is identical and supports all the same parameters and flags. This means that you can use the wsk deploy subcommand if you already have the CLI installed or follow the instructions below on installing the wskdeploy utility for standalone use.`

The above paragraph seems like it needs an update to point to the correct location of the deploy subcommand.

**Comment by dgrove-oss** [comment]
Good point.  The website is maintained here: https://github.com/apache/openwhisk-website.  In particular, the file _layouts/documentation.html  needs to be fixed up.
