### ISSUE TITLE
Description field/key is not supported for Rule entity

### ISSUE THREAD

**Issue by mrutkows** [apache/openwhisk-wskdeploy#548]
In theory, Rules should support the "Shared Entity schema" defined in the spec. which includes a descriotion, displayName and Annotations.  However, the grammar in v0.8.9 clearly has a description field (we can discuss whether Annotations are supported on Rules; they may not be now but Rules should have more control logic and importance going forward in the programming model).

yamlparser.go struct:
type Rule struct {
	//mapping to wsk.Rule.Trigger
	Trigger string `yaml:"trigger"` //used in manifest.yaml
	//mapping to wsk.Rule.Action
	Action string `yaml:"action"` //used in manifest.yaml
	Rule   string `yaml:"rule"`   //used in manifest.yaml
	//mapping to wsk.Rule.Name
	Name string
}

**Comment by pritidesai** [comment]
Annotations are supported in Rules.

**Comment by alvarolopez** [comment]
This but is valid also for the Packages and Actions:

    Error: manifest_parser.go [115]: [ERROR_YAML_PARSER_ERROR]: File: [manifest.yaml]: 
    ==> yaml: unmarshal errors:
    ==> line 3: field description not found in struct parsers.Package
    ==> line 10: field description not found in struct parsers.Action
