### ISSUE TITLE
wskdeploy does not respect WSK_CONFIG_FILE

### ISSUE THREAD

**Issue by rabbah** [apache/openwhisk-wskdeploy#809]
if you set `WSK_CONFIG_FILE`, the `wsk` cli will use its settings for wskprops. It appears that wskdeploy ignores this setting and always uses `~/.wskprops`.

**Comment by lionelvillard** [comment]
Have you tried `WSK_CONFIG_FILE`? @rabbah

**Comment by rabbah** [comment]
Thanks @lionelvillard - yes, I corrected the title and description.

**Comment by mrutkows** [comment]
See https://github.com/apache/incubator-openwhisk/blob/master/docs/cli.md#setting-up-the-openwhisk-cli 

documented as a "tip"
```
Tip: The OpenWhisk CLI stores the properties set in ~/.wskprops by default. The location of this file can be altered by setting the WSK_CONFIG_FILE environment variable.
```
documented Mar2017: https://github.com/apache/incubator-openwhisk/pull/2000

**Comment by rabbah** [comment]
bump - this is really a show stopper trying to deploy to multiple configurations.

Is there a suggested workaround that doesn't muck around with my `.wksprops` file?

**Comment by rabbah** [comment]
suggested workaround is using `-c` flag.
