### ISSUE TITLE
API Gateway doesn't take sequences into account

### ISSUE THREAD

**Issue by brunogirin** [apache/openwhisk-wskdeploy#854]
When writing a sequence that I want to expose via the API Gateway, I can set the `web` flag to `true` but `wskdeploy` doesn't see the sequence when creating the API.

### Manifest

```
packages:
  example:
    version: 0.0.1
    actions:
      greeting:
        function: build/libs/platform-0.0.1.jar
        runtime: java
        main: com.consideratehoteliers.Hello
        web-export: true
        inputs:
          name: string
        outputs:
          greeting: string
      copycat:
        function: build/libs/platform-0.0.1.jar
        runtime: java
        main: com.consideratehoteliers.Copy
    sequences:
      hello-copycat:
        actions: greeting, copycat
        web: true
    apis:
      hello-world:
        example:
          hello:
            greeting: GET
          hello-copy:
            hello-copycat: GET
```

### Output when running `wskdeploy`

```
$ wskdeploy
Info: The API host is [openwhisk.eu-gb.bluemix.net], from .wskprops.
Info: The auth key is set, from .wskprops.
Info: The namespace is [_], from .wskprops.
Info: The apigw access token is set, from .wskprops.
Info: Unmarshal OpenWhisk runtimes from internet at https://openwhisk.eu-gb.bluemix.net.
Error: manifestreader.go [98]: [ERROR_YAML_FILE_FORMAT_ERROR]: File: [manifest.yaml]: 
==> manifest_parser.go [1035]: [ERROR_YAML_FILE_FORMAT_ERROR]: File: [manifest.yaml]: Action [hello-copycat] is missing from manifest file, API [hello-world] can only be created based on the action from manifest file. Please update manifest file to include [hello-copycat] as a web action.
```

Also note that it looks like you need to set `web-export` for actions and `web` for sequences, which is rather confusing.

**Comment by mrutkows** [comment]
@brunogirin Are you using "latest" build, as Priti addressed some (if not all) of what you are describing in PR https://github.com/apache/incubator-openwhisk-wskdeploy/pull/834 which was merged late Monday afternoon Apr. 2 (this week, but not in release 0.9.2).

**Comment by brunogirin** [comment]
I'm using the latest release, which is 0.9.2 AFAIK. If it's fixed in code, that's fine, I'll happily test it again when it's released.

**Comment by brunogirin** [comment]
Note that I can't be sure of the exact version I'm running due to issue #855 but I believe it's 0.9.2.

**Comment by mrutkows** [comment]
@brunogirin if you want to try with "latest" release (i.e., built for each PR here: https://github.com/apache/incubator-openwhisk-wskdeploy/releases/tag/latest), it might be good to know if your test(s) work before we release 0.9.3 (which is not yet planned).  

Would rather know now if we need to fix additional things as we may not release a point version for another week or more and would appreciate confirmation in case we need to adjust plans.

**Comment by brunogirin** [comment]
@mrutkows "latest" is where I got my copy of the tool this morning so it should be up to date. Considering @pritidesai is on the case, I'm sure it will be fixed quickly and I will be happy to test when done.
